from pathlib import Path
import re,json
p=Path('presentacion/app.js');s=p.read_text(encoding='utf-8-sig')
m=re.search(r'const guides=(\[.*?\]);',s,re.S);g=json.loads(m[1]);g[2],g[3]=g[3],g[2]
g[2]='Llegamos a las 8:30 p. m. Encontramos una fila corta y una mesa disponible para cuatro en el primer piso. Nos sentamos, abrimos el QR y encontramos la publicidad del 3×1, cuyo horario ya había terminado. Pedimos cócteles y dos combos de sándwich con la oferta disponible. Reconocimos el entorno y enfocamos la observación en una mesa de cuatro adultos. Estuvimos hasta las 10 p. m.'
g[3]='La vista reúne seis elementos: verde y madera con luz tenue; entrada abierta que parecía zona de fumadores; mesas bajas, sofás y asientos sin respaldo; barra con botellas, lámpara de cristales y hojas; dos pisos conectados por escaleras a la derecha; y baño pequeño, cómodo, con vestíbulo compartido, espejos, un espacio de hombres y dos de mujeres. La música tenía presencia, pero permitía escucharnos. Las otras mesas no interrumpían y percibimos respeto. Los acolchados eran suaves y los objetos se percibían cuidados; algunos asientos no permitían recostar la espalda. El olor era neutro y el ambiente no se sentía encerrado ni caluroso. Sandía resultó suave y frutal; fresa con vodka tenía el alcohol más presente. Las preferencias variaron: a Juan no le gustó uno de los cócteles. Son percepciones del equipo.'
g[4]+=' La estrella identifica nuestro pedido: sandía, fresa con vodka y dos combos de sándwich. No es el pedido de la mesa observada.'
g=g[:7]+[
'Evaluar también requirió detenernos en detalles, como en el ejemplo de Henry y Karen. D01: ropa casual, camiseta de Carlos, relojes de las mujeres, pantalón beige recto y pelo partido al medio de Andrés; hubo dudas sobre el reloj del mayor. La chaqueta de Valentina pareció costosa y comentamos un posible nivel medio-alto de los jóvenes, sin comprobar marca ni estrato. D02: whisky aparente al comienzo, cócteles, cambios de sabor y promoción repetida; no confirmamos todos los nombres y bases. D03: Valentina y Carlos conversaban más, Andrés asentía y luego se integró; Patricia intervenía menos y después conversaba con Valentina. D04: manos al hablar, pitillo para señalar, caricia de Valentina en la cara de Andrés. D05: ambos hombres fueron al baño y Carlos tres veces; al final su marcha parecía menos estable. D06: música conversable, pantallas apagadas, QR, meseras sin uniforme, personal de cocina y barra uniformado; los cargos de los otros hombres no se confirmaron. Durante la observación surgieron seis hipótesis: posible familia y novio, atracción del 2×1, exploración de sabores, nivel socioeconómico, continuidad en una base de licor y posible previa a otra salida. Se conservan como preguntas.',
'Analizar significa seleccionar e interpretar lo que responde al objetivo. Repetir el 2×1 permite seguir el formato de elección; cambiar sabores conecta la oferta con el consumo; empezar con bebidas distintas muestra preferencias diferentes dentro de un grupo. Pasar de asentir a intervenir sugiere integración progresiva, sin probar jerarquías. El pitillo usado para señalar relaciona un objeto de consumo con la expresión. La caricia y el trato cercano sugieren confianza, pero no prueban parentesco. Las pausas y la marcha menos estable se conservan como cambios corporales, sin atribuir una causa comprobada. La música y las pantallas apagadas describen condiciones compatibles con conversar. La apariencia sirve para describir: no demuestra ingresos, marcas ni ocupaciones. Estas ocho lecturas convierten detalles aislados en material útil para la ideación posterior.',
'El registro de bebidas organiza tres momentos. Al comienzo los hombres tenían bebidas que parecían whisky y las mujeres cócteles en promoción. El nombre del primer cóctel no quedó confirmado: hubo referencias distintas durante la visita. Luego se observaron pares de sandía y naranja. Después llegaron otros cócteles y se repitió el 2×1. No medimos cantidades consumidas por persona ni confirmamos todas las bases de licor. Esta secuencia permite consultar el cambio de bebidas y el uso de la oferta.',
'Registrar deja evidencia consultable. Las cuatro fotografías muestran consumo y conversación, el gesto de Andrés, el entorno y la composición de la mesa. Se pueden ampliar desde cada polaroid. Cada foto está vinculada con los detalles seleccionados, pero una foto no prueba por sí sola toda la secuencia ni las intenciones. El registro escrito organiza acciones, cambios, pausas y dudas; el visual conserva estos cuatro momentos; el contexto reúne ubicación, carta y experiencia sensorial. La lámina anterior registra las bebidas. No usamos las imágenes para afirmar edades exactas, parentescos o nivel socioeconómico.',
'Concluimos seis cosas con respaldo en esta visita: el 2×1 fue una pauta repetida de pedido; la variedad de la carta se reflejó en cambios de cóctel; la participación en la conversación cambió; el pitillo y las manos acompañaron el habla; el consumo tuvo pausas y cambios corporales observables; y el entorno permitió conversar y resultó ameno para el equipo. Estos resultados aportan formatos de elección, variedad, dinámicas de grupo, usos de objetos, secuencia corporal y experiencia del lugar. Son insumos para idear, con el alcance de una mesa, cuatro adultos y 90 minutos.',
'Contrastamos las hipótesis que surgieron. H1: la cercanía es compatible con confianza, pero no confirma padres, hija y novio ni cuántas veces se habían reunido. H2: corroboramos el uso repetido de la promoción; no que fuera la razón de la visita ni quién conocía el lugar. H3: cambiar sabores apoya una lectura de exploración, aunque no se confirmó la intención. H4: la impresión de nivel medio-alto surgió por la apariencia y no permite verificar estrato. H5: no comprobamos las bases de todos los cócteles y al inicio había whisky aparente. H6: la idea de una previa surgió del ambiente y de otras salidas, pero no sabemos a dónde fue el grupo. Concluir también significa dejar abiertas las preguntas que el registro no resuelve.',
g[-1]]
s=s[:m.start()]+'const guides='+json.dumps(g,ensure_ascii=False)+';'+s[m.end():]
s=s.replace('pitch:55,bearing:-38,duration:reduce?0:8500','pitch:50,bearing:-30,duration:reduce?0:15000').replace('easing:t=>1-Math.pow(1-t,1.65)','easing:t=>t*t*(3-2*t)').replace('reduce?50:8600','reduce?50:15100').replace('duration:18000','duration:24000').replace('setTimeout(r,18050)','setTimeout(r,24050)')
s=s.replace('go(11)','go(slides.length-1)').replace('hash<=12','hash<=slides.length')
s=s.replace('closeDrawer();$("#lightbox").hidden=true;animateSlide','closeDrawer();closePhoto();animateSlide')
s=s.replace('if(e.key==="Escape"){closeDrawer();$("#lightbox").hidden=true;return}\n if(!$("#lightbox").hidden)return;', 'if(e.key==="Escape"){closeDrawer();closePhoto();return}\n if(!$("#lightbox").hidden){if(e.key==="ArrowRight"){e.preventDefault();openPhoto(photoIndex+1)}if(e.key==="ArrowLeft"){e.preventDefault();openPhoto(photoIndex-1)}return;}')
s=s.replace('function showDrawer(mode){','function showDrawer(mode){\n closePhoto();')
photos=json.loads(Path('presentacion/datos/photos-v4.json').read_text(encoding='utf-8-sig'))
js='''
const photos=PHOTOS;
let photoIndex=0,photoTrigger=null;
function openPhoto(n){
 photoIndex=(n+photos.length)%photos.length;const a=photos[photoIndex];closeDrawer();
 if($("#lightbox").hidden)photoTrigger=document.activeElement;
 $("#lightbox-content").innerHTML='<img src="assets/fotos/'+a[0]+'" alt="'+a[2]+'"><div class="photo-detail"><span>'+a[1]+' / REGISTRO FOTOGRÁFICO</span><h3>'+a[2]+'</h3><p>'+a[3]+'</p><small>'+a[4]+'</small></div>';
 $("#lightbox").hidden=false;$("#photo-tools").hidden=false;stage.classList.add("photo-open");$("#photo-count").textContent='Foto '+(photoIndex+1)+' / '+photos.length;
 gsap.fromTo('#lightbox-content',{opacity:0,y:12},{opacity:1,y:0,duration:reduce?.01:.35});$("#photo-close").focus();
}
function closePhoto(){if(!$("#lightbox").hidden){$("#lightbox").hidden=true;$("#photo-tools").hidden=true;stage.classList.remove("photo-open");photoTrigger?.focus();}}
$$("[data-photo]").forEach(b=>b.onclick=e=>{e.stopPropagation();openPhoto(+b.dataset.photo)});
$("#photo-prev").onclick=()=>openPhoto(photoIndex-1);$("#photo-next").onclick=()=>openPhoto(photoIndex+1);$("#photo-close").onclick=closePhoto;
$("#lightbox").onclick=e=>{if(e.target.id==='lightbox')closePhoto()};
$("#lightbox").setAttribute('role','dialog');$("#lightbox").setAttribute('aria-label','Registro fotográfico ampliado');
'''.replace('PHOTOS',json.dumps(photos,ensure_ascii=False))
s=s.replace('let tilesPromise;',js+'\nlet tilesPromise;')
s=s.replace('if(s.classList.contains("findings"))', '''if(s.querySelector('.inventory-symbol'))motion.fromTo(s.querySelectorAll('.inventory-symbol'),{scale:.5,rotation:-15},{scale:1,rotation:0,duration:.8,stagger:.12,ease:'back.out(1.5)'},.4);
 if(s.querySelector('.conclusion-icon'))motion.fromTo(s.querySelectorAll('.conclusion-icon'),{scale:.6},{scale:1,duration:1,stagger:.13,ease:'back.out(1.5)'},.45);
 if(s.querySelector('.hypothesis-marker'))motion.fromTo(s.querySelectorAll('.hypothesis-marker'),{scale:.4,rotation:-30},{scale:1,rotation:0,duration:.8,stagger:.13,ease:'back.out(1.6)'},.4);
 if(s.querySelector('.polaroid'))motion.fromTo(s.querySelectorAll('.polaroid'),{y:70,rotation:0,opacity:0},{y:0,rotation:i=>[-4,3,-2,4][i],opacity:1,duration:1.1,stagger:.17,ease:'power3.out'},.4);
 if(s.classList.contains("findings"))''')
p.write_text(s,encoding='utf-8');print('Guides',len(g))
