from pathlib import Path
import re,json
p=Path('presentacion/index.html');s=p.read_text(encoding='utf-8')
key='<aside class="person-key"><span>REFERENCIA · EDADES APROX.</span><div><b>Carlos <i>52</i></b><b>Patricia <i>48</i></b><b>Valentina <i>28</i></b><b>Andrés <i>29</i></b></div><small>Nombres ficticios · edades estimadas</small></aside>'
def heading(t,h):return f'<div class="phase-heading"><span class="phase-token">{t}</span><h2 class="reveal">{h}</h2></div>'+key
con=[('person','Carlos · conversación y pausas','Conversó con Valentina, pasó del whisky aparente a los cócteles y se ausentó tres veces al baño. Su ritmo alternó participación y pausas.','CAMBIO DE ELECCIÓN Y DE RITMO'),('person','Patricia · de menor intervención al diálogo','Al inicio habló menos; después conversó con Valentina. Su participación coexistió con los pedidos en promoción: el silencio inicial no define todo su papel.','PARTICIPACIÓN QUE CAMBIA'),('talk','Andrés · mayor presencia en el grupo','Pasó de asentir a hablar y gesticular con el pitillo. Es compatible con ganar confianza durante la reunión, sin aislar el papel del alcohol.','INTEGRACIÓN PROGRESIVA · H1/H6'),('hand','Valentina · cercanía entre interlocutores','Conversó con Carlos y Patricia y mostró afecto hacia Andrés. Podría estar conectando al joven con los mayores; el vínculo familiar es un supuesto.','POSIBLE PUENTE SOCIAL · H1'),('glass','Los pares · elecciones que se acercan','Los hombres se sumaron al 2×1 con sus acompañantes. Los cambios de sabor sugieren acuerdos o influencia mutua dentro de la mesa.','COORDINACIÓN E INFLUENCIA · H3/H5'),('sound','El grupo · compartir sin hacer lo mismo','Hubo conversación, pedidos, pausas individuales y una salida a dos. La reunión sostuvo distintas formas de participar alrededor del consumo.','CONVIVENCIA Y MOMENTOS A DOS · H7')]
h='<section class="slide conclusions-v4 conclusions-v5" data-title="Concluir: cómo interactuaron las cuatro personas" data-seconds="60">'+heading('04 / CONCLUIR · PERSONAS Y RELACIONES','Cuatro maneras de estar.<br><em>Una experiencia compartida.</em>')+'<div class="conclusion-grid">'
for n,(i,t,d,tag) in enumerate(con):h+=f'<article class="reveal"><div class="conclusion-icon"><svg><use href="#i-{i}"/></svg><b>0{n+1}</b></div><div><h3>{t}</h3><p>{d}</p><span>{tag}</span></div></article>'
h+='</div><div class="conclusion-scope reveal"><strong>1 mesa · 4 adultos · 90 minutos</strong><span>Deducciones situadas. Las posibles intenciones se contrastan a continuación.</span></div></section>'
s=re.sub(r'<section class="slide conclusions-v4.*?</section>',lambda m:h,s,count=1,flags=re.S)
hyp=[('H1','¿Un novio encontrando su lugar?','Lectura compatible','Imaginamos a Andrés integrándose a la familia de Valentina. Su mayor participación y la cercanía apoyan confianza; no confirman parentesco ni cuántas reuniones llevaban.'),('H2','¿El whisky como primera impresión?','Interpretación abierta','Pensamos que los hombres buscaban empezar más formales. Su elección inicial permite plantearlo, pero también puede responder simplemente al gusto.'),('H3','¿Ellas marcaron el siguiente pedido?','Secuencia compatible','Las mujeres ya usaban el 2×1; después los hombres se sumaron con sus acompañantes. Puede haber influencia, pero no escuchamos quién tomó la iniciativa.'),('H4','¿El 2×1 los había reunido allí?','Uso confirmado; motivo abierto','Pensamos que la promoción atrajo al grupo. La repitieron, aunque no sabemos si motivó la visita o se aprovechó una vez sentados.'),('H5','¿Probar juntos era parte del plan?','Lectura compatible','Cambiar sabores manteniendo los pares sugiere curiosidad compartida. Se confirma el cambio de pedidos, no la intención que lo produjo.'),('H6','¿Las rondas ayudaron a soltarse?','Coincidencia; causa abierta','Andrés habló y gesticuló más conforme avanzó la reunión. Tal vez ganó confianza con las bebidas, con el trato o con el tiempo; no pudimos separar esos factores.'),('H7','¿Necesitaban un momento a dos?','Cercanía visible; motivo abierto','Valentina y Andrés salieron juntos y volvieron de la mano. Pensamos en un espacio para hablar entre ellos; no sabemos qué ocurrió ni qué se dijeron.'),('H8','¿Alguien joven conocía el plan?','Sin corroborar','Pensamos que uno de los jóvenes conocía la promoción y había propuesto el lugar, quizá antes de otra salida. No confirmamos organizador ni destino posterior.')]
h='<section class="slide hypotheses-v4 hypotheses-v5" data-title="Concluir: ocho hipótesis y su alcance" data-seconds="50">'+heading('04 / CONCLUIR · LO QUE PENSAMOS Y LO QUE SOSTENEMOS','Detrás de cada gesto,<br><em>una pregunta sobre el vínculo.</em>')+'<div class="hypothesis-results">'
for c,t,st,d in hyp:h+=f'<article class="reveal"><div class="hypothesis-marker">{c}</div><div><h3>{t}</h3><span class="hypothesis-status">{st}</span><p>{d}</p></div></article>'
h+='</div><div class="hypothesis-close reveal"><b>La interacción cambió; las intenciones siguen abiertas.</b><span>Ese contraste es el insumo para idear.</span></div></section>'
s=re.sub(r'<section class="slide hypotheses-v4.*?</section>',lambda m:h,s,count=1,flags=re.S)
s=s.replace('estilos.css?v=4','estilos.css?v=5').replace('app.js?v=4','app.js?v=5').replace('01 / 14','01 / 13')
s=s.replace('Seleccionamos lo relevante: pedidos, cambios de bebida, conversación, gestos y desplazamientos.','Interpretamos cómo cambian las elecciones, la participación, la cercanía y las pausas alrededor de las bebidas.')
s=s.replace('Organizamos las observaciones y las fotografías en una secuencia que permite seguir lo ocurrido.','Conectamos hechos, lecturas y fotos en seis insumos claros sobre la interacción, listos para una ideación posterior.')
p.write_text(s,encoding='utf-8')
Path('presentacion/datos/v5-hypotheses.json').write_text(json.dumps(hyp,ensure_ascii=False),encoding='utf-8')
print('Slides',len(re.findall('class="slide ',s)),'seconds',sum(map(int,re.findall('data-seconds="(\\d+)"',s))))
