from pathlib import Path
import re,json
root=Path('presentacion');p=root/'index.html';s=p.read_text(encoding='utf-8')
def icon(n):return f'<svg><use href="#i-{n}"/></svg>'
key='<aside class="person-key"><span>REFERENCIA · EDADES APROX.</span><div><b>Carlos <i>52</i></b><b>Patricia <i>48</i></b><b>Valentina <i>28</i></b><b>Andrés <i>29</i></b></div><small>Nombres ficticios · edades estimadas</small></aside>'
def heading(token,title):return f'<div class="phase-heading"><span class="phase-token">{token}</span><h2 class="reveal">{title}</h2></div>'+key
def replace(cls,text):
 global s
 s=re.sub(r'<section class="slide '+cls+r'\b.*?</section>',lambda m:text,s,count=1,flags=re.S)
s=s.replace('Habla y gesticula con las manos.','Conversa con Valentina; va al baño tres veces.')
inv=[('person','Apariencia y detalles','Ropa casual, relojes en las mujeres y duda sobre el de Carlos. Andrés: pantalón beige y cabello partido al medio. La chaqueta de Valentina pareció costosa.'),('glass','De elecciones separadas a pares','Al inicio: whisky aparente para los hombres y 2×1 para las mujeres. Después, los hombres se suman al 2×1 con sus acompañantes; cambian los sabores.'),('talk','De escuchar a participar','Valentina y Carlos conversan más al comienzo. Andrés asiente y luego interviene más. Patricia habla menos al inicio; después conversa con Valentina.'),('hand','El cuerpo también conversa','Andrés es quien gesticula y señala con el pitillo. Valentina le acaricia la cara. Más adelante, los dos jóvenes regresan tomados de la mano.'),('stairs','Salidas solos y acompañados','Los hombres van al baño por separado. Carlos, tres veces; al final, marcha menos estable. También salen juntos Valentina y Andrés.'),('sound','La reunión se sostiene','Entre pedidos continúan hablando. Música que permite escucharse, televisores apagados y una mesa donde los interlocutores van cambiando.')]
html='<section class="slide inventory-v4 inventory-v5" data-title="Evaluar: detalles que abren preguntas" data-seconds="70">'+heading('01 / EVALUAR · DETALLES E HIPÓTESIS','La bebida cambia.<br><em>La relación también se mueve.</em>')+'<div class="observation-inventory">'
for n,(i,t,d) in enumerate(inv):html+=f'<article class="reveal"><div class="inventory-symbol">{icon(i)}<small>D0{n+1}</small></div><div><h3>{t}</h3><p>{d}</p></div></article>'
html+='</div><div class="hypothesis-seeds reveal"><span>NUESTRAS PREGUNTAS<br><b>Lecturas por contrastar.</b></span><div><span><b>H1–H2</b> ¿Integrarse y causar buena impresión?</span><span><b>H3–H4</b> ¿Seguir al otro y compartir el pedido?</span><span><b>H5–H6</b> ¿Explorar juntos y ganar confianza?</span><span><b>H7–H8</b> ¿Tener una pausa a dos y un plan previo?</span></div></div></section>'
replace('inventory-v4',html)
analysis=[('person','H2 · Una entrada más seria','Whisky aparente al inicio','Podría expresar una presentación más formal de Carlos y Andrés. También puede ser preferencia personal; la bebida no demuestra un rasgo de género.'),('glass','H3 · Seguir la elección del otro','Los hombres pasan al 2×1','El cambio hacia pedidos con sus acompañantes sugiere influencia mutua o acercamiento. No escuchamos quién propuso dejar el whisky.'),('glass','H4 · Ponerse de acuerdo','El 2×1 se repite por pares','La promoción coincide con elecciones coordinadas. Puede facilitar un acuerdo entre dos; no prueba que haya sido el motivo de llegar.'),('glass','H5 · Curiosidad compartida','Sandía, naranja y otros sabores','Cambiar juntos convierte la elección en una posible exploración compartida. No registramos sus comentarios sobre cada sabor.'),('talk','H1–H6 · Soltarse en la mesa','Andrés asiente → participa','A medida que avanza la reunión y el consumo, habla y gesticula más. Compatible con ganar confianza; tiempo, trato y bebida pueden concurrir.'),('hand','H6 · El vaso entra en el diálogo','Andrés usa manos y pitillo','El objeto deja de servir solo para beber y acompaña su expresión. La mayor gestualidad refuerza la lectura de una participación más activa.'),('person','H7 · Un momento entre dos','Salen juntos → vuelven de la mano','La cercanía de Valentina y Andrés se hace visible fuera de la mesa. Tal vez buscaban un momento propio; no sabemos qué conversaron.'),('stairs','Cambios en el ritmo de Carlos','Tres idas al baño y marcha distinta','Su participación alterna conversación y pausas. El cambio corporal coincide con la visita y el consumo; no se estableció una causa única.')]
html='<section class="slide analysis-v4 analysis-v5" data-title="Analizar: personas, vínculos y consumo" data-seconds="85">'+heading('02 / ANALIZAR · INTERACCIÓN CON EL ALCOHOL','Del pedido individual<br>al <em>ritmo de la mesa.</em>')+'<div class="interpretation-grid">'
for i,t,o,d in analysis:html+=f'<article class="reveal"><div class="interpret-icon">{icon(i)}</div><div class="interpret-observation"><small>{o}</small><h3>{t}</h3></div><i>→</i><p>{d}</p></article>'
html+='</div><div class="analysis-boundary reveal"><b>LECTURAS POSIBLES</b><span>Interpretamos conductas observadas. Las intenciones, el parentesco y el efecto causal del alcohol siguen abiertos.</span></div></section>'
replace('analysis-v4',html)
# A single Registrar slide, combining sequence, concepts and photographs.
old=re.search(r'<section class="slide registration-v4.*?</section>',s,re.S)[0]
gallery=re.search(r'<div class="polaroid-gallery">.*?</button></div>',old,re.S)[0]
gallery=gallery.replace('polaroid-gallery','record-photos')
gallery=re.sub(r'<p>.*?</p>','',gallery)
records=[('R1','Elegir con alguien','Pedidos separados → cócteles por pares.','Insumo: acuerdos e influencia entre acompañantes.'),('R2','Probar como actividad común','Cambian sabores y mantienen el 2×1.','Insumo: curiosidad compartida durante la reunión.'),('R3','Entrar en la conversación','Andrés pasa de asentir a intervenir más.','Insumo: cómo se construye la confianza.'),('R4','Expresarse con un objeto','Andrés gesticula y señala con el pitillo.','Insumo: gestos y usos sociales alrededor del vaso.'),('R5','Acercarse y apartarse','Caricia; salida de los jóvenes; regreso de la mano.','Insumo: momentos de pareja dentro de un grupo.'),('R6','Pausar y volver a la mesa','Carlos va al baño tres veces; cambia su marcha.','Insumo: ritmos individuales durante el encuentro.')]
def drinks(colors):return '<div class="record-cups">'+''.join(f'<div class="drink {"short" if c=="amber" else "tall"} {c}"><i></i>'+(''if c=='amber'else'<b></b>')+'</div>'for c in colors)+'</div>'
html='<section class="slide registration-v5" data-title="Registrar: seis insumos de interacción" data-seconds="75">'+heading('03 / REGISTRAR · ORGANIZAR PARA IDEAR DESPUÉS','Lo observado se vuelve<br><em>materia prima.</em>')+'<div class="record-sequence">'
for n,(cs,t,d) in enumerate([(['amber','amber','cream','cream'],'01 · Elecciones distintas','Hombres: whisky aparente.<br>Mujeres: cócteles 2×1.'),(['watermelon','watermelon','orange','orange'],'02 · Pedidos en pares','Sandía y naranja.<br>Los hombres se suman al 2×1.'),(['violet','violet','mint','mint'],'03 · La dinámica continúa','Otros cócteles, más conversación.<br>Nombres y cantidades no confirmados.')]):html+=f'<article class="reveal">{drinks(cs)}<div><h3>{t}</h3><p>{d}</p></div></article>'
html+='</div><div class="record-insumos">'
for c,t,o,d in records:html+=f'<article class="reveal"><span>{c}</span><div><h3>{t}</h3><p>{o}</p><small>{d}</small></div></article>'
html+='</div>'+gallery+'<div class="record-note">Registro sintetizado de la visita · Colores de bebidas ilustrativos · Fotos ampliables con clic · Los insumos aún no son propuestas creativas.</div></section>'
replace('drinks','');replace('registration-v4',html)
p.write_text(s,encoding='utf-8')
(root/'datos/v5-analysis.json').write_text(json.dumps(analysis,ensure_ascii=False),encoding='utf-8')
