from pathlib import Path
import json
rows=[
{'icon':'person','title':'Cuatro personas de dos edades','observation':'Carlos y Patricia parecían mayores que Valentina y Andrés. Vestían de forma casual; los relojes, la chaqueta y el pantalón llamaron la atención del equipo.','analysis':'Las diferencias de edad ayudan a seguir quién conversa con quién y cómo se forman los pares al pedir. La ropa sirve para reconocerlos; no permite saber sus ingresos ni si son familia.','record':'Quién comparte mesa: Carlos ≈52, Patricia ≈48, Valentina ≈28 y Andrés ≈29. Conservar la composición del grupo y los vínculos por confirmar.','conclusion':'Compartieron la salida personas de dos edades distintas. El posible parentesco y el nivel medio-alto quedaron como preguntas, no como datos.'},
{'icon':'glass','title':'Al principio pidieron distinto','observation':'Carlos y Andrés tenían bebidas que parecían whisky. Patricia y Valentina tomaban cócteles en 2×1. No quedó claro el nombre del primer cóctel.','analysis':'Al empezar, los hombres eligieron por separado y las mujeres compartieron una promoción. Puede haber gustos distintos o más confianza entre ellas para acordar un pedido; no sabemos por qué eligieron así.','record':'Inicio: whisky aparente para Carlos y Andrés; cócteles 2×1 para Patricia y Valentina. Guardar quién elige solo y quién acuerda una bebida con alguien.','conclusion':'Estar en la misma mesa no significó empezar bebiendo lo mismo. La diferencia inicial ayuda a reconocer cómo se acercaron después sus elecciones.'},
{'icon':'glass','title':'Los hombres se sumaron al 2×1','observation':'Después, Carlos y Andrés dejaron el whisky aparente y pidieron cócteles en promoción con sus respectivas acompañantes. El 2×1 se volvió a repetir.','analysis':'Los pedidos de los hombres se acercaron a lo que ya tomaban las mujeres. Es posible que ellas los animaran o que acordaran aprovechar la oferta. El cambio se vio; quién convenció a quién no se escuchó.','record':'Cambio: de elecciones separadas a pedidos por pares. Conservar el antes y el después como insumo sobre acuerdos e influencia entre acompañantes.','conclusion':'La elección de bebida pasó a organizarse en pares. La influencia de las mujeres es una explicación posible, pero no quedó confirmada.'},
{'icon':'glass','title':'Cambiaron los sabores entre pedidos','observation':'Llegaron cócteles de sandía y naranja; después, otros diferentes. Mantuvieron el 2×1. No se confirmaron todos los sabores ni las bases de licor.','analysis':'Cambiar de sabor mientras repiten la promoción sugiere que querían probar juntos, además de beber. La elección podía ser parte del momento compartido; no registramos qué opinaban de cada sabor.','record':'Secuencia: cócteles iniciales → sandía y naranja → otros cócteles. Guardar la repetición del formato y el cambio de sabores como exploración compartida.','conclusion':'Repitieron la manera de pedir, pero cambiaron lo que tomaban. Esto apoya la idea de curiosidad por probar sabores durante la reunión.'},
{'icon':'talk','title':'Andrés empezó a participar más','observation':'Al comienzo Andrés asentía mientras Valentina y Carlos hablaban. Conforme avanzaron la reunión y las bebidas, Andrés intervino más en la conversación.','analysis':'Andrés pareció sentirse más cómodo con el grupo. Beber juntos pudo ayudar, pero también pasó más tiempo conversando. No se puede atribuir ese cambio solo al alcohol ni saber si era una presentación familiar.','record':'Participación de Andrés: escuchar y asentir → intervenir más. Conservar ese cambio junto con el avance del encuentro, sin adjudicarle una causa única.','conclusion':'Andrés ganó presencia en la conversación. Su integración es visible; que fuera un novio conociendo a la familia o un efecto del alcohol sigue siendo supuesto.'},
{'icon':'talk','title':'La conversación cambió de interlocutores','observation':'Primero hablaron más Valentina y Carlos. Patricia intervino menos al inicio; después conversó con Valentina y Andrés también aportó. La música permitía escucharse.','analysis':'La atención no quedó siempre en las mismas personas. Entre pedidos se abrieron otras conversaciones: Patricia participó y Valentina habló tanto con Carlos como con ella. La reunión siguió siendo compartida.','record':'Conversación: Valentina–Carlos → Patricia–Valentina, con intervenciones de Andrés. Guardar quién habla, escucha y se incorpora mientras continúan los pedidos.','conclusion':'Patricia tuvo más participación de la que mostraba al comienzo. Valentina conectó con varios integrantes; pudo ayudar a acercar al joven a los mayores.'},
{'icon':'hand','title':'Andrés hablaba con las manos y el pitillo','observation':'Andrés era quien movía las manos al hablar. Usaba el pitillo para señalar, además de tenerlo en su bebida. Este gesto no se atribuye a Carlos.','analysis':'La bebida también estaba presente en su forma de hablar: el pitillo se volvió un apoyo para señalar y expresarse. Junto con sus intervenciones, el gesto muestra una participación más activa.','record':'Gesto de Andrés: mano en movimiento y pitillo usado para señalar. Conservar la acción y la foto como insumo sobre usos del objeto mientras se conversa.','conclusion':'La relación con la bebida incluyó más que tomarla. En Andrés, el pitillo acompañó el habla y ayudó a hacer visible su participación.'},
{'icon':'person','title':'Los jóvenes mostraron cercanía','observation':'Valentina acarició la cara de Andrés. En otro momento salieron juntos al baño y regresaron tomados de la mano. No se supo qué hablaron durante esa salida.','analysis':'Los gestos apoyan la idea de una relación afectiva. Salir juntos pudo darles un momento para hablar a solas o comentar cómo se sentían, pero eso no se observó. La cercanía sí quedó registrada.','record':'Cercanía: caricia → salida de Valentina y Andrés → regreso de la mano. Guardar los momentos a dos dentro de la salida grupal, sin inventar su conversación.','conclusion':'Los jóvenes mantuvieron un vínculo cercano dentro del encuentro. Los gestos son compatibles con una pareja; el motivo de la salida conjunta permanece abierto.'},
{'icon':'stairs','title':'Carlos hizo más pausas durante la visita','observation':'Los hombres fueron al baño por separado. Carlos se levantó tres veces; en la última ocasión su marcha se veía menos estable. Luego seguía dentro de la reunión.','analysis':'Carlos alternó conversación, consumo y salidas de la mesa. La bebida pudo influir en esas pausas y en su forma de caminar, pero no comprobamos la causa ni cuánto había tomado.','record':'Ritmo de Carlos: tres idas al baño y marcha menos estable en la última. Guardar cantidad de pausas y cambio corporal, sin calcular consumo ni diagnosticarlo.','conclusion':'La misma reunión tuvo ritmos distintos para cada persona. En Carlos fueron más visibles las pausas y un cambio corporal; su causa no quedó establecida.'}
]
hyps=[
('Relaciones','¿Será que Valentina es hija de Carlos y Patricia?','No confirmado','Valentina conversó con ambos y mostró cercanía. Eso no permite asegurar que sean sus padres.'),
('Relaciones','¿Será que Andrés es el novio de Valentina y está conociendo a su familia?','Compatible; parentesco abierto','La caricia, la mano y su mayor participación apoyan cercanía, pero no confirman una presentación familiar.'),
('Relaciones','¿Será la segunda o tercera salida de Andrés con la familia de Valentina?','No se pudo comprobar','Al equipo le pareció que ya había confianza. No conocíamos sus encuentros anteriores.'),
('Apariencia','¿Será que Valentina y Andrés son de un nivel socioeconómico medio-alto por su ropa y accesorios?','Impresión sin verificar','La idea surgió por su apariencia. No sabemos marcas, ingresos ni estrato.'),
('Primer pedido','¿Será que Carlos y Andrés eligieron whisky para verse más serios al empezar la reunión?','Explicación posible','Se observó whisky aparente. También pudieron elegirlo por gusto; no conocimos su intención.'),
('Primer pedido','¿Será que Patricia y Valentina pidieron el 2×1 porque, como posible mamá e hija, les resultaba fácil ponerse de acuerdo?','Pedido visible; relación abierta','Compartieron la promoción al inicio. No se comprobó el parentesco ni la razón del acuerdo.'),
('Cambio de pedido','¿Será que Patricia y Valentina convencieron a Carlos y Andrés de seguir con el 2×1?','La secuencia lo permite','Los hombres se sumaron después. No escuchamos quién propuso el cambio.'),
('Cambio de pedido','¿Será que los cuatro querían probar distintos sabores aprovechando el 2×1?','Apoyada por los cambios','Cambiaron los cócteles y repitieron la promoción. Eso apoya la exploración, sin confirmar el propósito.'),
('Elección del lugar','¿Será que Valentina o Andrés conocían el 2×1 y propusieron llevar a los mayores a Yumi Yumi?','Sin comprobar','El uso repetido de la oferta no revela quién eligió el sitio ni qué motivó la visita.'),
('Confianza','¿Será que compartir las bebidas ayudó a Andrés a perder la timidez y participar más?','Cambio visible; causa abierta','Andrés se involucró más. También avanzaron el tiempo y la conversación; no aislamos el efecto del alcohol.'),
('Momento a dos','¿Será que Valentina y Andrés salieron juntos para hablar de cómo se estaban sintiendo en la reunión?','No sabemos el motivo','Volvieron de la mano. La conversación y la intención de esa pausa quedaron fuera de la observación.'),
('Plan de la noche','¿Será que el grupo estaba tomando y comiendo antes de continuar la noche en otro lugar?','Sin comprobar','La idea surgió del ambiente y de otras salidas. No conocimos el destino posterior de esta mesa.')
]
Path('presentacion/datos/v7-content.json').write_text(json.dumps({'rows':rows,'hypotheses':hyps},ensure_ascii=False),encoding='utf-8')
