from pathlib import Path
import json
p=Path('presentacion/datos/v7-content.json');d=json.loads(p.read_text(encoding='utf-8'));r=d['rows']
new=[
('Personas de edades distintas','Carlos y Patricia son los mayores; Valentina y Andrés, los jóvenes. La chaqueta de Valentina, el buzo tipo polo y el pantalón beige de Andrés proyectan una apariencia cuidada y un nivel medio-alto.','La salida reúne a los padres de Valentina con ella y su novio. Las diferencias de edad y de confianza ayudan a entender quién toma la iniciativa, quién escucha y cómo se forman los pares al pedir.','La mesa reúne dos generaciones y una relación que se está integrando a la familia. Compartir el plan permite acercar a personas que llegan con distintos niveles de confianza.'),
('Al principio pidieron distinto','Carlos y Andrés empezaron con whisky. Patricia y Valentina compartieron cócteles en 2×1. Los primeros pedidos separaron la elección de los hombres del acuerdo entre las mujeres.','Carlos y Andrés arrancan con una elección más seria e individual. Patricia y Valentina aprovechan su confianza de madre e hija para acordar el 2×1 y compartir la elección desde el comienzo.','El primer pedido muestra dos formas de entrar a la reunión: Carlos y Andrés afirman una elección propia; Patricia y Valentina empiezan compartiendo una decisión.'),
('Los hombres se sumaron al 2×1','Después, Carlos y Andrés dejaron el whisky y pidieron cócteles en promoción con sus respectivas acompañantes. El 2×1 se volvió a repetir a lo largo de la visita.','Patricia y Valentina acercan a Carlos y Andrés a la dinámica que ellas ya compartían. El cambio de bebida pasa a ser un acuerdo entre acompañantes y una forma de participar en el mismo plan.','Las mujeres influyeron en el siguiente pedido y los hombres se sumaron. La bebida dejó de ser solo una elección individual y se convirtió en una decisión compartida.'),
('Cambiaron los sabores entre pedidos','Los cuatro probaron cócteles de sandía y naranja; más adelante llegaron otros sabores. Mantuvieron el 2×1 mientras continuaban conversando y compartiendo la mesa.','Repetir la promoción y cambiar los sabores convierte el consumo en una exploración compartida. Elegir qué probar después añade decisiones en común y mantiene activa la experiencia de los cuatro.','La curiosidad por probar sabores sostuvo nuevos pedidos y nuevas elecciones en compañía. El 2×1 les permitió repetir ese pequeño plan dentro de la reunión.'),
('Andrés empezó a participar más','Andrés empezó tímido: escuchaba y asentía mientras Valentina y Carlos hablaban. Conforme avanzaron las bebidas y la conversación, ganó confianza y comenzó a intervenir con más soltura.','Andrés pasa de estar pendiente de los demás a sentirse parte del grupo. Compartir bebidas, tiempo y conversación le da un ambiente para relajarse, mostrarse y participar en la reunión familiar.','Andrés dejó atrás la reserva inicial y encontró su lugar en la conversación. La experiencia compartida acompañó su integración con Carlos, Patricia y Valentina.'),
('La conversación cambió de interlocutores','Primero hablaron más Valentina y Carlos. Patricia participó menos al inicio; después conversó con Valentina y Andrés también aportó. La música permitía escucharse con facilidad.','Entre pedidos se abren otras conversaciones y la atención empieza a circular. Patricia gana espacio y Valentina conecta al novio con sus padres, mientras Andrés empieza a aportar con mayor confianza.','La reunión fue dando espacio a distintas voces. Patricia participó más y Valentina actuó como puente entre Andrés y sus padres, sosteniendo la integración del grupo.'),
('Andrés empezó a expresarse con el cuerpo','Al ganar confianza, Andrés no solo habló más: acompañó sus palabras con las manos y con gestos amplios. El pitillo entró en esos movimientos como parte de una expresión cada vez más suelta.','Los gestos muestran cómo fue saliendo la personalidad de Andrés. Pasó de una presencia reservada a una forma más espontánea de expresarse; su voz, sus manos y sus movimientos comenzaron a trabajar juntos.','La confianza de Andrés se hizo visible en todo su cuerpo. El cambio importante fue su mayor soltura y expresividad: empezó a mostrar su personalidad frente al grupo.'),
('Valentina y Andrés mostraron afecto','Valentina acarició la cara de Andrés. Andrés primero había ido solo al baño; en otra ocasión salió acompañado de Valentina y los dos regresaron tomados de la mano.','Valentina y Andrés combinan la convivencia familiar con un espacio propio de pareja. La salida juntos les da un momento para acercarse y comentar cómo están viviendo la reunión antes de volver a la mesa.','Valentina y Andrés mantuvieron momentos de afecto dentro del plan familiar. La caricia, la pausa juntos y el regreso de la mano muestran esa alternancia entre pareja y grupo.'),
('Carlos llevó un ritmo con más pausas','Carlos se levantó tres veces para ir al baño. En la última salida se veía mareado y caminaba con menor estabilidad. Su presencia en la mesa se interrumpía con más frecuencia que la de los demás.','Carlos alternó conversación, bebidas y salidas al baño. Las tres pausas y el mareo visible al caminar muestran que su cuerpo llevaba otro ritmo, aunque siguiera participando de la misma reunión.','Compartir mesa y pedidos no significó vivir el consumo al mismo ritmo. En Carlos se hicieron más visibles las pausas y el mareo; su experiencia tuvo interrupciones y cambios corporales propios.')]
for row,(t,o,a,c) in zip(r,new):row.update(title=t,observation=o,analysis=a,conclusion=c)
answers=[('Vínculo familiar','Valentina se relaciona con Carlos y Patricia desde la confianza de hija: conversa con ambos y sirve de enlace con Andrés.'),('Integración del novio','Andrés entra reservado al encuentro familiar y encuentra mayor confianza al compartir bebidas y conversación con los padres de Valentina.'),('Confianza en construcción','La escena encaja en una segunda o tercera salida: Andrés aún se muestra tímido al inicio, pero ya tiene cercanía para participar y mostrarse.'),('Estilo de los jóvenes','La ropa y los accesorios sitúan a Valentina y Andrés en el perfil medio-alto construido para esta mesa, con una apariencia casual cuidada.'),('Primera impresión','Carlos y Andrés arrancan con whisky para presentarse más serios. Después relajan esa elección y se incorporan a los cócteles por pares.'),('Acuerdo entre madre e hija','Patricia y Valentina usan su cercanía para acordar el 2×1 desde el principio. La promoción comienza como una elección compartida entre ellas.'),('Influencia entre acompañantes','Patricia y Valentina animan a Carlos y Andrés a sumarse al 2×1. La elección de ellas se transforma en la dinámica de toda la mesa.'),('Curiosidad compartida','Los cuatro aprovechan el 2×1 para probar sabores diferentes. Cada nuevo pedido renueva una decisión que disfrutan en compañía.'),('Iniciativa de los jóvenes','Valentina y Andrés acercan a los mayores a un lugar de cócteles y promociones. El plan permite reunir generaciones alrededor de una experiencia común.'),('Mayor soltura de Andrés','Las bebidas y la conversación acompañan su confianza. Andrés habla más, se expresa con las manos y deja que su personalidad salga a flote.'),('Espacio propio de la pareja','Valentina y Andrés aprovechan una pausa juntos para conectar fuera de la mesa. El regreso de la mano sostiene esa cercanía al volver al grupo.'),('Inicio de la noche','Yumi Yumi funciona como primera parada del plan: compartir comida, cócteles y conversación antes de continuar la salida.')]
for h,(status,body) in zip(d['hypotheses'],answers):h[2]=status;h[3]=body
p=Path('presentacion/datos/v8-content.json');p.write_text(json.dumps(d,ensure_ascii=False),encoding='utf-8')
