from pathlib import Path
import re,json,html
root=Path('presentacion');p=root/'index.html';s=p.read_text(encoding='utf-8')
items=[('Compartir entre edades','Dos mayores y dos jóvenes pasan a compartir cócteles.','Explorar qué facilita disfrutar un mismo plan entre personas de edades distintas.'),('Elegir solos o acompañados','Ellos empiezan con whisky aparente; ellas comparten el 2×1.','Explorar cuándo pesa el gusto propio y cuándo se acuerda una bebida con alguien.'),('Sumarse al pedido del otro','Los hombres después piden el 2×1 con sus acompañantes.','Explorar cómo una recomendación o un acuerdo cambia lo que alguien decide tomar.'),('Probar como plan compartido','Cambian sabores y mantienen los pedidos en pares.','Explorar la elección de un nuevo sabor como momento para compartir curiosidad.'),('Ganar voz en la reunión','Andrés pasa de asentir a hablar más mientras avanza el encuentro.','Explorar cómo beber y conversar juntos acompañan la confianza, sin asegurar qué la causa.'),('Abrir espacio a otras voces','Patricia interviene más; Valentina conversa con distintos integrantes.','Explorar cómo un encuentro alrededor de las bebidas permite incorporarse a la conversación.'),('Expresarse con el pitillo','Andrés señala con el pitillo mientras habla y mueve las manos.','Considerar los objetos de la bebida como parte del gesto y de la expresión social.'),('Pasar del grupo a la pareja','Caricia, salida juntos y regreso de Valentina y Andrés de la mano.','Explorar cómo una salida con bebidas combina cercanía de pareja y convivencia del grupo.'),('Reconocer ritmos personales','Carlos hace tres pausas; al final camina menos estable.','Considerar pausas y cambios de comodidad al pensar la experiencia, sin asumir igual consumo.')]
m=re.search(r'<section class="slide registration-v5.*?</section>',s,re.S);reg=m[0]
b='<div class="record-insumos">'+''.join(f'<article class="reveal"><span>{i+1:02}</span><div><h3>{t}</h3><p>{o}</p><small><b>Para idear:</b> {u}</small></div></article>'for i,(t,o,u) in enumerate(items))+'</div>'
reg=re.sub(r'<div class="record-insumos">.*?(?=<div class="record-photos">)',lambda m:b,reg,flags=re.S)
reg=reg.replace('03 · La dinámica continúa','03 · Otros pedidos').replace('Otros cócteles, más conversación.<br>Nombres y cantidades no confirmados.','Otros cócteles y conversación.<br>Nombres sin confirmar.')
reg=reg.replace('Lo observado se vuelve<br><em>materia prima.</em>','Conductas alrededor de la bebida.<br><em>Insumos para crear después.</em>')
reg=reg.replace('Registro sintetizado de la visita · Colores de bebidas ilustrativos · Fotos ampliables con clic · Los insumos aún no son propuestas creativas.','Hecho observado → posibilidad para idear · Las conductas coinciden con el consumo, pero no prueban que el alcohol las cause · Clic en las fotos para ampliar.')
s=s[:m.start()]+reg+s[m.end():];p.write_text(s,encoding='utf-8')
p=root/'app.js';js=p.read_text(encoding='utf-8');m=re.search(r'const guides=(\[.*?\]);',js,re.S);g=json.loads(m[1]);g[10]='Registrar conserva hechos concretos y explica cómo usarlos para una creación posterior. '+' '.join(f'{t}. Observamos: {o} Para idear: {u}'for t,o,u in items)+' Estas son posibilidades de exploración, no ideas publicitarias ya resueltas ni efectos demostrados del alcohol.';js=js[:m.start()]+'const guides='+json.dumps(g,ensure_ascii=False)+';'+js[m.end():];p.write_text(js,encoding='utf-8')
