from pathlib import Path
import re,json
p=Path('presentacion/index.html');s=p.read_text(encoding='utf-8-sig')
def icon(n):return f'<svg><use href="#i-{n}"/></svg>'
# Arrival precedes perception.
a=re.search(r'<section class="slide senses.*?</section>',s,re.S).group();b=re.search(r'<section class="slide space.*?</section>',s,re.S).group()
steps=[('person','Llegamos','8:30 p. m. · Fila corta. Había una mesa disponible para cuatro.'),('person','Nos sentamos','Primer piso. Desde la mesa reconocimos el ambiente y la barra.'),('qr','Abrimos el QR','La carta digital abrió con un anuncio de 3×1; ya no aplicaba.'),('glass','Pedimos','Elegimos cócteles y dos combos de sándwich. Aprovechamos el 2×1.'),('focus','Enfocamos la mirada','Reconocimos el entorno y elegimos una mesa de cuatro adultos.')]
b=re.sub(r'<div class="journey-objects">.*?</section>', '<div class="arrival-five">'+''.join(f'<article class="reveal"><div class="arrival-art">{icon(i)}<b>0{n+1}</b></div><h3>{t}</h3><p>{d}</p></article>' for n,(i,t,d) in enumerate(steps))+'<div class="arrival-line"></div></div><div class="journey-bottom reveal"><span>DE LA EXPERIENCIA A LA OBSERVACIÓN</span><p>Primero vivimos el lugar; después seguimos las interacciones de una mesa.<br>La visita terminó a las 10:00 p. m.</p></div></section>',b,flags=re.S)
a='''<section class="slide sensory-v4" data-title="Percibir con cinco sentidos" data-seconds="50"><div class="section-heading"><p class="eyebrow reveal">EL LUGAR / EXPERIENCIA DEL EQUIPO</p><h2 class="reveal">Un ambiente que invita<br>a <em>quedarse y conversar.</em></h2></div><div class="sensory-photo reveal"><img src="assets/fotos/foto-f62da75.webp" alt="Ambiente interior de Yumi Yumi"><i></i></div><div class="visual-world reveal"><div class="sense-label">'''+icon('eye')+'''<h3>Vista</h3><span>LO QUE VIMOS · CÓMO SE SINTIÓ</span></div><div class="visual-details">'''
visual=[('◐','Verde + madera','Luz tenue, tonos amenos, tapizado de rombos y franjas verde/blanco.'),('↳','Abierto → interior','Entrada abierta que parecía zona de fumadores; adentro, luz más baja.'),('▱','Mobiliario bajo','Mesas bajas, sofás para grupos y asientos sin respaldo. Se veía acogedor.'),('✧','Barra protagonista','Botellas, lámpara de cristales y hojas en cascada. Cajas junto a la barra.'),('↗','Dos niveles','Escaleras a la derecha. Bebidas abajo; más mesas, cocina y baño arriba.'),('◇','Baño pequeño y cómodo','Vestíbulo compartido y espejos; un baño de hombres y dos de mujeres. Discreto.')]
a+=''.join(f'<article><b>{i}</b><div><h4>{t}</h4><p>{d}</p></div></article>'for i,t,d in visual)+'</div></div><div class="other-senses">'
rest=[('sound','Oído',['Música agradable, volumen medio-alto.','Nos escuchábamos bien al conversar.','Las otras mesas no nos interrumpían; percibimos respeto.']),('hand','Tacto',['Acolchado suave en sillas y sofás.','Mobiliario y vasos se percibían cuidados.','Algunos asientos no permitían apoyar la espalda.']),('nose','Olfato',['Olor neutro, sin molestias.','Sin olor marcado a alcohol o encierro.','Ambiente agradable, sin calor agobiante.']),('glass','Gusto',['Sandía: suave y frutal.','Fresa con vodka: alcohol más presente.','Gustos distintos: a Juan no le agradó uno.'])]
a+=''.join(f'<article class="reveal"><div class="sense-label">{icon(i)}<h3>{t}</h3></div><ul>'+''.join(f'<li>{x}</li>'for x in ds)+'</ul></article>'for i,t,ds in rest)+'</div><div class="sensory-caption">Sensaciones del equipo durante la visita · El consumo de la mesa observada se presenta por separado.</div></section>'
s=re.sub(r'<section class="slide senses.*?</section>',b,s,flags=re.S,count=1)
s=re.sub(r'<section class="slide space.*?</section>',a,s,flags=re.S,count=1) if False else s
# The first replacement inserted arrival; replace original arrival (second match) with sensory.
arr=list(re.finditer(r'<section class="slide space.*?</section>',s,re.S));m=arr[-1];s=s[:m.start()]+a+s[m.end():]
s=s.replace('data-seconds="75"','data-seconds="70"').replace('data-seconds="70"><div class="phase-heading"><span class="phase-token">02','data-seconds="65"><div class="phase-heading"><span class="phase-token">02').replace('data-seconds="55"><div class="phase-heading"><span class="phase-token">04','data-seconds="50"><div class="phase-heading"><span class="phase-token">04')
s=s.replace('<p class="offer-source">','<div class="team-order reveal"><b>★ LO QUE PEDIMOS</b><span>Sandía suave y frutal</span><span>Fresa con vodka</span><span>Dos combos de sándwich</span><small>Experiencia del equipo</small></div><p class="offer-source">')
s=s.replace('Identificamos patrones visibles y conservamos los resultados como insumos para una ideación posterior.','Deducimos a partir del registro, contrastamos las hipótesis y reunimos insumos para idear después.')
p.write_text(s,encoding='utf-8')
print('Slides',len(re.findall('class="slide ',s)),'seconds',sum(map(int,re.findall('data-seconds="(\\d+)"',s))))
