from pathlib import Path
import re,json,html
root=Path('presentacion');p=root/'index.html';s=p.read_text(encoding='utf-8')
rows=[('focus','Evaluar','Cuatro personas, dos formas de empezar.','En Yumi Yumi, el sábado 26 de septiembre, de 8:30 a 10:00 p. m., Carlos (≈52), Patricia (≈48), Valentina (≈28) y Andrés (≈29), vestidos de forma casual, compartían una mesa: <b>los hombres empezaron con whisky aparente y las mujeres con cócteles 2×1</b>. Valentina conversaba con Carlos; Andrés asentía y Patricia intervenía menos. Su cercanía hizo pensar en una familia y un novio, sin confirmarlo.'),('eye','Analizar','Las elecciones se acercan; la participación cambia.','Después, los hombres se sumaron al 2×1 con sus acompañantes: <b>lo que empezó como elecciones separadas pudo volverse un acuerdo compartido</b>. El whisky quizá respondía a una primera impresión más formal; el cambio, a influencia mutua. Al variar sabores y avanzar la reunión, Andrés participó más: una posible integración favorecida por el trato, el tiempo y las bebidas, sin poder separar sus efectos.'),('note','Registrar','Pedidos, gestos y pausas cuentan la secuencia.','Llegaron pares de sandía y naranja, luego otros cócteles; el 2×1 se repitió. Andrés habló con las manos y señaló con el pitillo; Patricia conversó con Valentina. Esta acarició a Andrés y, tras salir juntos, <b>los jóvenes regresaron de la mano</b>. Carlos fue tres veces al baño y al final mostró una marcha menos estable: elecciones coordinadas, participación creciente, cercanía y ritmos individuales.'),('check','Concluir','Compartir bebidas no significó participar igual.','Carlos alternó conversación y pausas; Patricia pasó a intervenir; Andrés ganó presencia y Valentina pudo conectar al joven con los mayores. <b>Los pedidos convergieron mientras cada persona encontró su manera de estar en el grupo</b>. La escena es compatible con confianza e influencia mutua; la posible familia, el novio en integración, la atracción del 2×1 y una pausa íntima siguen siendo hipótesis, no certezas.')]
h='<section class="slide synthesis-v5" data-title="Síntesis: así cambió el encuentro" data-seconds="40"><div class="section-heading"><p class="eyebrow reveal">SÍNTESIS / LA HISTORIA DE LA MESA OBSERVADA</p><h2 class="reveal">Una noche, cuatro personas.<br><em>Así cambió su encuentro.</em></h2></div><div class="synthesis-flow">'
for n,(i,t,d,r) in enumerate(rows):h+=f'<article class="reveal"><div class="synthesis-icon"><svg><use href="#i-{i}"/></svg><span>0{n+1}</span></div><div class="synthesis-phase"><h3>{t}</h3><p>{d}</p></div><div class="synthesis-bridge"></div><p class="synthesis-result">{r}</p></article>'
h+='</div><div class="synthesis-foot">Una mesa · 90 minutos · Nombres ficticios y edades estimadas · Las posibles motivaciones se mantienen como hipótesis.</div></section>'
s=re.sub(r'<section class="slide synthesis-v5.*?</section>',lambda m:h,s,count=1,flags=re.S).replace('estilos.css?v=5','estilos.css?v=6').replace('app.js?v=5','app.js?v=6');p.write_text(s,encoding='utf-8')
p=root/'app.js';s=p.read_text(encoding='utf-8');m=re.search(r'const guides=(\[.*?\]);',s,re.S);g=json.loads(m[1]);g[12]=' '.join(html.unescape(re.sub('<[^>]+>','',r[3])) for r in rows);s=s[:m.start()]+'const guides='+json.dumps(g,ensure_ascii=False)+';'+s[m.end():];p.write_text(s,encoding='utf-8')
p=root/'INSTRUCCIONES.txt';s=p.read_text(encoding='utf-8-sig').replace('VERSIÓN 5','VERSIÓN 6').replace('Síntesis de las cuatro fases antes del agradecimiento.','Síntesis narrativa del encuentro: los hechos, su lectura, la secuencia y las conclusiones, antes del agradecimiento.');p.write_text(s,encoding='utf-8')
p=root/'scripts/empaquetar-v5.py';(root/'scripts/empaquetar-v6.py').write_text(p.read_text(encoding='utf-8-sig').replace('Presentacion_v5','Presentacion_v6'),encoding='utf-8')
