from pathlib import Path
import re,json,html
root=Path('presentacion');p=root/'index.html';s=p.read_text(encoding='utf-8')
rows=[('focus','Evaluar','Cómo se vivió el encuentro.','En Yumi Yumi, durante 90 minutos, Carlos (≈52), Patricia (≈48), Valentina (≈28) y Andrés (≈29) compartieron mesa. <b>Andrés se mostraba tímido: escuchaba y asentía mientras Valentina hablaba con Carlos.</b> Patricia participaba menos. Ellos empezaron con bebidas distintas a los cócteles 2×1 de ellas; luego pidieron por pares y cambiaron sabores. Andrés fue ganando confianza: habló más y señaló con el pitillo. Valentina le acarició la cara. Él había ido solo al baño; en otra ocasión salió con ella y regresaron de la mano. Carlos se levantó tres veces y al final caminaba menos estable.'),('eye','Analizar','Qué pueden significar esos cambios.','<b>La reunión pasó de elecciones separadas a una experiencia más compartida.</b> Los hombres pudieron dejarse animar por sus acompañantes para pedir el 2×1; probar otros sabores les daba nuevas decisiones en común. Andrés dejó de limitarse a escuchar y empezó a ocupar su lugar en la conversación. Compartir bebidas pudo acompañar esa confianza, junto con el tiempo y el trato. Patricia también encontró momentos para hablar y Valentina conectó con distintos integrantes. La caricia y la salida juntos sugieren cercanía: imaginamos un momento a dos para comentar cómo iban sintiéndose. Las pausas de Carlos muestran que no todos llevaban el mismo ritmo.'),('note','Registrar','Las escenas que alimentan nuevas ideas.','<b>De esta mesa quedan escenas concretas para volver a mirar:</b> dos edades compartiendo un plan; hombres y mujeres que empiezan eligiendo distinto; un pedido que se extiende a los acompañantes; sandía, naranja y luego otros sabores; Andrés que pasa de escuchar a participar; Patricia que entra al diálogo; un pitillo que sirve para señalar; una caricia y un regreso de la mano; Carlos que interrumpe su permanencia tres veces. Son insumos para explorar acuerdos al pedir, curiosidad compartida, confianza al conversar, usos sociales de los objetos, afecto dentro del grupo y pausas personales. Las cuatro fotos acompañan las escenas visibles.'),('check','Concluir','Cómo terminó de leerse aquella mesa.','<b>Compartir bebidas acompañó una reunión en la que las personas fueron acercando sus elecciones y mostrando distintas formas de confianza.</b> Andrés ganó presencia; Patricia habló más; Valentina sostuvo conversaciones con los mayores y momentos de afecto con Andrés; Carlos alternó conversación y pausas. Esto hace comprensible nuestra idea de un novio que busca integrarse, de unas mujeres que pudieron influir en los pedidos y de una pareja que pudo necesitar un momento propio. Son lecturas de lo visto: no sabemos si eran familia, si era su segunda o tercera salida, qué hablaron fuera de la mesa ni cuánto del cambio se debió al alcohol.')]
h='<section class="slide synthesis-v5 synthesis-v7" data-title="Síntesis: cómo cambió la interacción de la mesa" data-seconds="40"><div class="section-heading"><p class="eyebrow reveal">SÍNTESIS / EL ENCUENTRO, SUS CAMBIOS Y LO QUE NOS DEJA</p><h2 class="reveal">Andrés empezó escuchando.<br><em>La mesa fue ganando confianza.</em></h2></div><div class="synthesis-flow">'
for n,(i,t,d,r) in enumerate(rows):h+=f'<article class="reveal"><div class="synthesis-icon"><svg><use href="#i-{i}"/></svg><span>0{n+1}</span></div><div class="synthesis-phase"><h3>{t}</h3><p>{d}</p></div><div class="synthesis-bridge"></div><p class="synthesis-result">{r}</p></article>'
h+='</div><div class="synthesis-foot">Nombres ficticios y edades estimadas · Timidez, confianza y posibles motivos son lecturas del equipo; las relaciones no se confirmaron.</div></section>'
s=re.sub(r'<section class="slide synthesis-v5.*?</section>',lambda m:h,s,count=1,flags=re.S);p.write_text(s,encoding='utf-8')
p=root/'app.js';js=p.read_text(encoding='utf-8');m=re.search(r'const guides=(\[.*?\]);',js,re.S);g=json.loads(m[1]);g[13]=' '.join(html.unescape(re.sub('<[^>]+>','',r[3]))for r in rows);js=js[:m.start()]+'const guides='+json.dumps(g,ensure_ascii=False)+';'+js[m.end():];p.write_text(js,encoding='utf-8')
