from pathlib import Path
import re,json
p=Path('presentacion/index.html');s=p.read_text(encoding='utf-8')
rows=[('focus','Evaluar','Definir qué, quién, dónde y cuándo.','<b>Foco:</b> interacción con bebidas alcohólicas. <b>Mesa:</b> Carlos (≈52), Patricia (≈48), Valentina (≈28) y Andrés (≈29). <b>Lugar y tiempo:</b> Yumi Yumi, primer piso, sábado 26 de septiembre, 8:30–10:00 p. m. Describimos apariencia, pedidos, conversación, gestos y salidas; surgieron ocho hipótesis.'),('eye','Analizar','Seleccionar e interpretar lo relevante.','El whisky aparente y los cócteles iniciales dieron paso al 2×1 por pares: posible influencia y acuerdos. Los sabores cambiaron mientras continuó el encuentro. Andrés participó más y usó el pitillo al hablar; los jóvenes mostraron cercanía. Carlos alternó conversación y pausas. Interpretamos relaciones, sin asegurar intenciones ni causas.'),('note','Registrar','Convertir los datos en insumos claros.','Organizamos la secuencia de bebidas, cuatro fotografías y seis núcleos: <b>elegir con alguien, probar juntos, entrar en la conversación, expresarse con un objeto, acercarse y apartarse, pausar y volver.</b> Cada núcleo conecta un hecho con una lectura útil para idear después y conserva lo que no pudimos confirmar.'),('check','Concluir','Deducir y contrastar las hipótesis.','Los participantes no actuaron igual: Carlos cambió de elección y ritmo; Patricia ganó presencia; Andrés se integró más; Valentina pudo servir de puente. Los pedidos convergieron y hubo momentos de pareja dentro del grupo. La confianza y la influencia son lecturas compatibles; parentesco, motivos y efecto del alcohol siguen abiertos.')]
h='<section class="slide synthesis-v5" data-title="Síntesis: de la observación al insumo" data-seconds="40"><div class="section-heading"><p class="eyebrow reveal">SÍNTESIS / LAS CUATRO FASES EN UNA MIRADA</p><h2 class="reveal">Así convertimos una visita<br>en <em>insumos para idear.</em></h2></div><div class="synthesis-flow">'
for n,(i,t,d,r) in enumerate(rows):h+=f'<article class="reveal"><div class="synthesis-icon"><svg><use href="#i-{i}"/></svg><span>0{n+1}</span></div><div class="synthesis-phase"><h3>{t}</h3><p>{d}</p></div><div class="synthesis-bridge"></div><p class="synthesis-result">{r}</p></article>'
h+='</div><div class="synthesis-foot">Una mesa · 90 minutos · Nombres ficticios y edades estimadas · Evidencia e interpretación se conservan diferenciadas.</div></section>'
s=s.replace('<section class="slide thanks"',h+'\n<section class="slide thanks"')
# Allocate 40 seconds to the synthesis, preserving ten minutes overall.
for cls in ['cover','space','sensory-v4','method','evaluate-v3','inventory-v4','analysis-v4','registration-v5']:
 pat=r'(<section class="slide '+cls+r'\b[^>]*data-seconds=")(\d+)(")'
 s=re.sub(pat,lambda m:m[1]+str(int(m[2])-5)+m[3],s,count=1)
s=s.replace('01 / 13','01 / 14');p.write_text(s,encoding='utf-8')
print('Slides',len(re.findall('class="slide ',s)),'seconds',sum(map(int,re.findall('data-seconds="(\\d+)"',s))))
