from pathlib import Path
import re,json,html
root=Path('presentacion');p=root/'index.html';s=p.read_text(encoding='utf-8')
s=s.replace('<a href="assets/fuentes/carta-original.pdf" target="_blank">Carta original ↗</a>','<a href="assets/fuentes/carta-original.pdf" target="_blank">Ver carta ↗</a><a href="assets/fuentes/carta-original.pdf" download="Carta-Yumi-Yumi.pdf">↓ Descargar carta</a>')
rows=[('focus','Evaluar','Lo que mostraba la mesa.','Carlos (≈52), Patricia (≈48), Valentina (≈28) y Andrés (≈29) compartían una mesa del primer piso de Yumi Yumi el 26 de septiembre, de 8:30 a 10:00 p. m. Vestían casual; relojes y ropa hicieron pensar en un nivel medio-alto, sin comprobarlo. <b>Ellos tenían whisky aparente y ellas cócteles 2×1; luego los hombres se sumaron a la promoción y cambiaron los sabores.</b> Andrés pasó de asentir a hablar y señalar con el pitillo; Patricia conversó más con Valentina. Los jóvenes mostraron afecto y volvieron de la mano; Carlos hizo tres pausas para ir al baño.'),('eye','Analizar','Lo que esos detalles dicen de su interacción.','Los pedidos iniciales muestran distintas maneras de elegir: individualmente o compartiendo una promoción. <b>El paso de los hombres al 2×1 puede reflejar un acuerdo o la influencia de sus acompañantes</b>; variar sabores sugiere curiosidad compartida. Andrés parecía ganar confianza al hablar y gesticular más, aunque también avanzaban el tiempo y el trato. Patricia se incorporó y Valentina habló con distintos integrantes. La salida de los jóvenes sugiere un momento a dos; las pausas y la marcha de Carlos muestran otro ritmo dentro de la misma reunión.'),('note','Registrar','Los detalles que quedan como insumos.','Quedan nueve insumos conectados con esas lecturas: <b>grupo de dos edades; elecciones iniciales distintas; paso al pedido por pares; sabores nuevos dentro del 2×1; mayor participación de Andrés; cambios de interlocutores; pitillo usado para señalar; momentos de cercanía a dos; pausas de Carlos.</b> La secuencia conserva whisky aparente y cócteles → sandía/naranja → otros cócteles; la cercanía, caricia → salida juntos → regreso de la mano; las pausas, tres idas al baño y marcha menos estable al final. Cuatro fotos acompañan los hechos visibles; motivos, parentescos y cantidades quedan sin confirmar.'),('check','Concluir','Lo que podemos sostener sobre ellos.','<b>La mesa pasó de elecciones distintas a pedidos compartidos, pero cada persona participó a su manera.</b> Carlos alternó conversación y pausas; Patricia intervino más; Andrés ganó presencia y usó el pitillo al hablar; Valentina se relacionó con los mayores y mostró afecto hacia Andrés. Los cambios apoyan una lectura de acuerdos, curiosidad y confianza. No prueban que fueran padres, hija y novio, que fuera su segunda o tercera salida, ni su estrato. Tampoco confirman quién propuso el sitio, quién convenció a quién, el motivo de la pausa a dos o cuánto influyó el alcohol. Lo comprobado y lo pendiente quedan disponibles para idear.')]
h='<section class="slide synthesis-v5 synthesis-v7" data-title="Síntesis: observaciones, análisis, registros y conclusión" data-seconds="40"><div class="section-heading"><p class="eyebrow reveal">SÍNTESIS / LA INFORMACIÓN COMPLETA DEL ENCUENTRO</p><h2 class="reveal">Cuatro personas alrededor de una mesa.<br><em>Del detalle a la conclusión.</em></h2></div><div class="synthesis-flow">'
for n,(i,t,d,r) in enumerate(rows):h+=f'<article class="reveal"><div class="synthesis-icon"><svg><use href="#i-{i}"/></svg><span>0{n+1}</span></div><div class="synthesis-phase"><h3>{t}</h3><p>{d}</p></div><div class="synthesis-bridge"></div><p class="synthesis-result">{r}</p></article>'
h+='</div><div class="synthesis-foot">Nombres ficticios · Edades estimadas · Hechos observados e interpretaciones conservan su diferencia.</div></section>'
s=re.sub(r'<section class="slide synthesis-v5.*?</section>',lambda m:h,s,count=1,flags=re.S);p.write_text(s,encoding='utf-8')
# Align every guide with its corresponding slide after adding the hypothesis page.
p=root/'app.js';js=p.read_text(encoding='utf-8');m=re.search(r'const guides=(\[.*?\]);',js,re.S);old=json.loads(m[1]);g=old[:7]
sections=re.findall(r'<section class="slide .*?</section>',s,re.S)
for sec in sections[7:-1]:
 sec=re.sub(r'<aside class="person-key">.*?</aside>','',sec,flags=re.S);sec=re.sub(r'<svg.*?</svg>','',sec,flags=re.S)
 t=html.unescape(re.sub('<[^>]+>',' ',sec));g.append(re.sub(r'\s+',' ',t).strip())
g.append(old[-1]);js=js[:m.start()]+'const guides='+json.dumps(g,ensure_ascii=False)+';'+js[m.end():]
js=js.replace('motion=gsap.timeline();','motion=gsap.timeline();')
p.write_text(js,encoding='utf-8');print('Guiones',len(g))
